/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next/es/alert')['Alert']
    TButton: typeof import('tdesign-vue-next/es/button')['Button']
    TCard: typeof import('tdesign-vue-next/es/card')['Card']
    TCol: typeof import('tdesign-vue-next/es/grid')['Col']
    TCollapse: typeof import('tdesign-vue-next/es/collapse')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next/es/collapse')['CollapsePanel']
    TContent: typeof import('tdesign-vue-next/es/layout')['Content']
    TDivider: typeof import('tdesign-vue-next/es/divider')['Divider']
    TDropdown: typeof import('tdesign-vue-next/es/dropdown')['Dropdown']
    TFooter: typeof import('tdesign-vue-next/es/layout')['Footer']
    THeadMenu: typeof import('tdesign-vue-next/es/menu')['HeadMenu']
    TInput: typeof import('tdesign-vue-next/es/input')['Input']
    TLayout: typeof import('tdesign-vue-next/es/layout')['Layout']
    TMenuItem: typeof import('tdesign-vue-next/es/menu')['MenuItem']
    ToolLayout: typeof import('./src/components/ToolLayout.vue')['default']
    TRow: typeof import('tdesign-vue-next/es/grid')['Row']
    TSlider: typeof import('tdesign-vue-next/es/slider')['Slider']
    TSpace: typeof import('tdesign-vue-next/es/space')['Space']
    TSwitch: typeof import('tdesign-vue-next/es/switch')['Switch']
    TTag: typeof import('tdesign-vue-next/es/tag')['Tag']
    TTextarea: typeof import('tdesign-vue-next/es/textarea')['Textarea']
  }
}
